version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: inventorydb
      MYSQL_USER: java_user
      MYSQL_PASSWORD: temp_pass
    ports:
      - "3306:3306"
    volumes:
      - mysqldb_data:/var/lib/mysql

  app:
    build: .
    container_name: demo_app
    environment:
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_NAME: inventorydb
      DB_USERNAME: java_user
      DB_PASSWORD: temp_pass
    ports:
      - "8080:8080"
    depends_on:
      mysqldb:
        condition: service_started
 
 
volumes:
  mysqldb_data:
